Loading画面を作成、表示
erikoenuma/Yumemi-Inc-ios-codecheck pull request #23
Opened 2021-04-05 09:35 UTC by Eriko-creator

#22 
Loading画面の表示方法として、storyboardでpopupViewのようなものを作成し、WKNavigationDelegateを使用してローディング中に表示させました。
SPMで新たにLottieをダウンロードしています。

- レビューして欲しい点
  - 初めてpopupViewを作ってみたので設計が合っているかどうか
  -API通信を行っている時にも同じ画面を表示したいと思い、エラーの際にLoading画面→Loading画面終了→UIAlertContoller という順番で表示するためにDispatchqueue.main.asyncAfterを使ったが正しいのかどうか

- 保留にしていること
  - WKWebViewのエラー処理
  - 別issueでDetailViewにReadmeを表示させようと思っているためscrollView上にstackViewを乗せた状態にしています

よろしくお願いいたします。

2021-04-05 11:41 UTC, sakiyamaK requested changes
@Eriko-creator コメントしました

2021-04-05 11:41 UTC, sakiyamaK commented on iOSEngineerCodeCheck/View/LoadingView/LoadingView.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
<img src="https://i.gyazo.com/534e97693c4f80c794129c8980476bb5.png" />

謎の+1が気になります

2021-04-05 11:41 UTC, sakiyamaK commented on iOSEngineerCodeCheck/Controller/LoadingViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(finishAnimating), name: .finishLoading, object: nil)
NotificationCenterはどこからでも呼べてしまうカプセル化と真逆の行為なので最終手段です。
Loadingが終わったら何かしたいだけなら普通にfunctionを用意したらいいです。

```
func finishAnimation() {
  self.dismiss(animated: false, completion: nil)
}
```

```
class HogeViewController {
  func hogehoge() {
 　let loading = //LoadingViewControllerを呼び出したとする
     //非同期処理してるとする
     //非同期処理が終わった
     loading.finisAnimation() //普通にこうしてメソッドを呼び出せばいい
  }
}
```



ですが、今回のようにただdismissしたいだけなら呼び出し側で素直にdismissしたらいいです

```
class HogeViewController {
  func hogehoge() {
 　let loading = //LoadingViewControllerを呼び出したとする
     //非同期処理してるとする
     //非同期処理が終わった
     loading.dismiss(animated: false, completion: nil) //普通にdismiss
  }
}
```

2021-04-05 11:41 UTC, sakiyamaK commented on iOSEngineerCodeCheck/Controller/LoadingViewController.swift
> +    }
autolayoutとそれ以外のレイアウト方式を組み合わせるのも複雑になりやすいです
コードで制約を貼れるようになりましょう。
調べたらやり方も出てきますしsnapkitを使うと楽に貼れます
分からなければ講義もあります

2021-04-05 11:41 UTC, sakiyamaK commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
> +        guard let load = storyboard.instantiateViewController(identifier: "load") as? LoadingViewController else { return }
"LoadingView"というハードコーディングをやめましょう
またこのVCは常にStoryboardから呼び出すのでこういうstaticメソッドを用意しましょう

```
class LoadingViewController {
  static func makeFromStoryboard() -> LoadingViewController {
    UIStoryboard(name: "LoadingView", bundle: nil).instantiateViewController(identifier: "load") as! LoadingViewController
  }
} 
```

```
class HogeViewController {
  func hogehoge() {
 　let loading = LoadingViewController.makeFromStoryboard()
  }
}
```
```

2021-04-05 11:41 UTC, sakiyamaK commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
> +                    }
switchをControllerで書くことはほとんどありません

```
enum APIError: Error{
    case searchWordEmpty
    case invalidURL
    case networkError
    case unknown

   func showAlert(from: UIViewController) {
     UIAlertController.showAPIErrorAlert(error: self, from)
   }
}
```

呼び出し側

```
case .failure(let error):
   DispatchQueue.main.asyncAfter(deadline: .now()+0.5){
     error.showAlert(from: self)
   }
```

2021-04-06 12:37 UTC, Eriko-creator commented on iOSEngineerCodeCheck/View/LoadingView/LoadingView.storyboard
> +<?xml version="1.0" encoding="UTF-8"?>
削除しました。色々いじった過程で1が残ってしまっていました。失礼いたしました。

2021-04-06 12:37 UTC, Eriko-creator commented on iOSEngineerCodeCheck/Controller/LoadingViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(finishAnimating), name: .finishLoading, object: nil)
修正しました！
WKNavigationDelegateの各メソッドで同じLoadingViewControllerを呼び出せないと思ってNotificationを使用していましたが、LoadingViewControllerをインスタンス変数に代入することで解決しました。

2021-04-06 12:37 UTC, Eriko-creator commented on iOSEngineerCodeCheck/Controller/LoadingViewController.swift
> +    }
修正しました。snapkit使ったことないので今度使ってみます！ありがとうございます。

2021-04-06 12:37 UTC, Eriko-creator commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
> +        guard let load = storyboard.instantiateViewController(identifier: "load") as? LoadingViewController else { return }
天才すぎてびっくりしました。修正しました。

2021-04-06 12:37 UTC, Eriko-creator commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
> +                    }
修正しました。

2021-04-06 12:38 UTC, Eriko-creator commented
コメント返しました。

2021-04-06 12:45 UTC, sakiyamaK requested changes
@Eriko-creator コメントしました

2021-04-06 12:45 UTC, sakiyamaK commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
>                  }
画面の更新は非同期で動きます
これではロードがdismissしきる前にアラートが出ておかしくなる可能性がありまふ
dismissが終わったあと、つまりcompletionにnilではなく無名関数を登録してそこでアラートを表示しましょう

2021-04-06 12:53 UTC, Eriko-creator commented on iOSEngineerCodeCheck/Controller/SearchViewController.swift
>                  }
修正しました。

2021-04-06 12:53 UTC, Eriko-creator commented
コメント返しました。

2021-04-06 12:55 UTC, sakiyamaK approved these changes
@Eriko-creator LGTMでえええす！

2021-04-06 12:56 UTC, merged